// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework;

namespace Linq2Rest.Parser
{
	public partial class ExpressionTokenizerTests
	{
[Test]
[PexGeneratedBy(typeof(ExpressionTokenizerTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void GetArithmeticTokenThrowsArgumentNullException131()
{
    TokenSet tokenSet;
    tokenSet = this.GetArithmeticToken((string)null);
}
[Test]
[PexGeneratedBy(typeof(ExpressionTokenizerTests))]
public void GetArithmeticToken716()
{
    TokenSet tokenSet;
    tokenSet = this.GetArithmeticToken("");
    PexAssert.IsNull((object)tokenSet);
}
[Test]
[PexGeneratedBy(typeof(ExpressionTokenizerTests))]
public void GetArithmeticToken46()
{
    TokenSet tokenSet;
    tokenSet = this.GetArithmeticToken("\0");
    PexAssert.IsNull((object)tokenSet);
}
[Test]
[PexGeneratedBy(typeof(ExpressionTokenizerTests))]
public void GetArithmeticToken224()
{
    TokenSet tokenSet;
    tokenSet = this.GetArithmeticToken(" ");
    PexAssert.IsNull((object)tokenSet);
}
[Test]
[PexGeneratedBy(typeof(ExpressionTokenizerTests))]
public void GetArithmeticToken327()
{
    TokenSet tokenSet;
    tokenSet = this.GetArithmeticToken("\0\0\0");
    PexAssert.IsNull((object)tokenSet);
}
[Test]
[PexGeneratedBy(typeof(ExpressionTokenizerTests))]
public void GetArithmeticToken129()
{
    TokenSet tokenSet;
    tokenSet = this.GetArithmeticToken("add");
    PexAssert.IsNotNull((object)tokenSet);
}
[Test]
[PexGeneratedBy(typeof(ExpressionTokenizerTests))]
public void GetArithmeticToken727()
{
    TokenSet tokenSet;
    tokenSet = this.GetArithmeticToken(" \0");
    PexAssert.IsNull((object)tokenSet);
}
	}
}
