// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework;

namespace Linq2Rest.Parser
{
	public partial class ExpressionTokenizerTests
	{
[Test]
[PexGeneratedBy(typeof(ExpressionTokenizerTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void GetTokensThrowsContractException522()
{
    try
    {
      IEnumerable<TokenSet> iEnumerable;
      iEnumerable = this.GetTokens((string)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(ExpressionTokenizerTests))]
public void GetTokens911()
{
    IEnumerable<TokenSet> iEnumerable;
    iEnumerable = this.GetTokens("");
    PexAssert.IsNotNull((object)iEnumerable);
}
	}
}
