// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Explorable;
using Microsoft.Pex.Framework;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace Linq2Rest.Parser
{
	public partial class FunctionTokenSetTests
	{
[Test]
[PexGeneratedBy(typeof(FunctionTokenSetTests))]
public void ToString01710()
{
    FunctionTokenSet functionTokenSet;
    string s;
    functionTokenSet = PexInvariant.CreateInstance<FunctionTokenSet>();
    PexInvariant.SetField<string>((object)functionTokenSet, "_left", "");
    PexInvariant.SetField<string>((object)functionTokenSet, "_right", "");
    PexInvariant.SetField<string>((object)functionTokenSet, "_operation", "");
    PexInvariant.CheckInvariant((object)functionTokenSet);
    s = this.ToString01(functionTokenSet);
    PexAssert.AreEqual<string>("  ", s);
    PexAssert.IsNotNull((object)functionTokenSet);
}
	}
}
