// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Reflection;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace Linq2Rest.Parser
{
	public partial class MemberNameResolverTests
	{
[Test]
[PexGeneratedBy(typeof(MemberNameResolverTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ResolveNameThrowsArgumentNullException358()
{
    string s;
    MemberNameResolver s0 = new MemberNameResolver();
    s = this.ResolveName(s0, (MemberInfo)null);
}
	}
}
