// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Linq2Rest;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Linq2Rest.Parser.Moles;
using Linq2Rest.Moles;
using Microsoft.Pex.Framework;

namespace Linq2Rest.Parser
{
	public partial class SelectExpressionFactoryTTests
	{
[Test]
[PexGeneratedBy(typeof(SelectExpressionFactoryTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException187()
{
    SelectExpressionFactory<int> selectExpressionFactory;
    selectExpressionFactory =
      this.Constructor<int>((IMemberNameResolver)null, (IRuntimeTypeProvider)null);
}
[Test]
[PexGeneratedBy(typeof(SelectExpressionFactoryTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException157()
{
    SIMemberNameResolver sIMemberNameResolver;
    SelectExpressionFactory<int> selectExpressionFactory;
    sIMemberNameResolver = new SIMemberNameResolver();
    selectExpressionFactory = this.Constructor<int>
                                  ((IMemberNameResolver)sIMemberNameResolver, (IRuntimeTypeProvider)null);
}
[Test]
[PexGeneratedBy(typeof(SelectExpressionFactoryTTests))]
public void Constructor781()
{
    SIMemberNameResolver sIMemberNameResolver;
    SIRuntimeTypeProvider sIRuntimeTypeProvider;
    SelectExpressionFactory<int> selectExpressionFactory;
    sIMemberNameResolver = new SIMemberNameResolver();
    sIRuntimeTypeProvider = new SIRuntimeTypeProvider();
    selectExpressionFactory =
      this.Constructor<int>((IMemberNameResolver)sIMemberNameResolver, 
                            (IRuntimeTypeProvider)sIRuntimeTypeProvider);
    PexAssert.IsNotNull((object)selectExpressionFactory);
}
	}
}
