// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Web.UI.WebControls;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework;

namespace Linq2Rest.Parser
{
	public partial class SortDescriptionTTests
	{
[Test]
[PexGeneratedBy(typeof(SortDescriptionTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException700()
{
    SortDescription<int> sortDescription;
    sortDescription =
      this.Constructor<int>((Func<int, object>)null, SortDirection.Ascending);
}
[Test]
[PexGeneratedBy(typeof(SortDescriptionTTests))]
public void Constructor416()
{
    SortDescription<int> sortDescription;
    sortDescription = this.Constructor<int>
                          (PexChoose.CreateDelegate<Func<int, object>>(), SortDirection.Ascending);
    PexAssert.IsNotNull((object)sortDescription);
    PexAssert.AreEqual<SortDirection>
        (SortDirection.Ascending, sortDescription.Direction);
    PexAssert.IsNotNull(sortDescription.KeySelector);
}
	}
}
