// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Web.UI.WebControls;
using Microsoft.Pex.Framework.Explorable;
using Microsoft.Pex.Framework;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace Linq2Rest.Parser
{
	public partial class SortDescriptionTTests
	{
[Test]
[PexGeneratedBy(typeof(SortDescriptionTTests))]
public void DirectionGet307()
{
    SortDescription<int> sortDescription;
    SortDirection i;
    sortDescription = PexInvariant.CreateInstance<SortDescription<int>>();
    PexInvariant.SetField<Func<int, object>>((object)sortDescription, 
                                             "_keySelector", PexChoose.CreateDelegate<Func<int, object>>());
    PexInvariant.SetField<SortDirection>
        ((object)sortDescription, "_direction", SortDirection.Ascending);
    PexInvariant.CheckInvariant((object)sortDescription);
    i = this.DirectionGet<int>(sortDescription);
    PexAssert.AreEqual<SortDirection>(SortDirection.Ascending, i);
    PexAssert.IsNotNull((object)sortDescription);
    PexAssert.AreEqual<SortDirection>
        (SortDirection.Ascending, sortDescription.Direction);
    PexAssert.IsNotNull(sortDescription.KeySelector);
}
	}
}
