// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace Linq2Rest.Parser
{
	public partial class TokenSetTests
	{
[Test]
[PexGeneratedBy(typeof(TokenSetTests))]
public void Constructor107()
{
    TokenSet tokenSet;
    tokenSet = this.Constructor();
    PexAssert.IsNotNull((object)tokenSet);
}
	}
}
