// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;
using Linq2Rest.Provider.Moles;
using Microsoft.Pex.Framework;

namespace Linq2Rest.Provider
{
	public partial class ExpressionProcessorTests
	{
[Test]
[PexGeneratedBy(typeof(ExpressionProcessorTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException710()
{
    try
    {
      ExpressionProcessor expressionProcessor;
      expressionProcessor = this.Constructor((IExpressionVisitor)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(ExpressionProcessorTests))]
public void Constructor499()
{
    SIExpressionVisitor sIExpressionVisitor;
    ExpressionProcessor expressionProcessor;
    sIExpressionVisitor = new SIExpressionVisitor();
    expressionProcessor = this.Constructor((IExpressionVisitor)sIExpressionVisitor);
    PexAssert.IsNotNull((object)expressionProcessor);
}
	}
}
