// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Linq.Expressions;
using Microsoft.Pex.Framework;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace Linq2Rest.Provider
{
	public partial class ExpressionVisitorTests
	{
[Test]
[PexGeneratedBy(typeof(ExpressionVisitorTests))]
public void Visit290()
{
    string s;
    ExpressionWriter s0 = new ExpressionWriter();
    s = this.Visit(s0, (Expression)null);
    PexAssert.AreEqual<string>((string)null, s);
    PexAssert.IsNotNull((object)s0);
}
	}
}
