// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework;

namespace Linq2Rest.Provider
{
	public partial class ParameterBuilderTests
	{
[Test]
[PexGeneratedBy(typeof(ParameterBuilderTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException718()
{
    try
    {
      ParameterBuilder parameterBuilder;
      parameterBuilder = this.Constructor((Uri)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(ParameterBuilderTests))]
public void Constructor851()
{
    Uri uri;
    ParameterBuilder parameterBuilder;
    uri = new Uri("  \\\\-");
    parameterBuilder = this.Constructor(uri);
    PexAssert.IsNotNull((object)parameterBuilder);
}
[Test]
[PexGeneratedBy(typeof(ParameterBuilderTests))]
public void Constructor85101()
{
    Uri uri;
    ParameterBuilder parameterBuilder;
    uri = new Uri("  \\\\0");
    parameterBuilder = this.Constructor(uri);
    PexAssert.IsNotNull((object)parameterBuilder);
}
[Test]
[PexGeneratedBy(typeof(ParameterBuilderTests))]
public void Constructor85102()
{
    Uri uri;
    ParameterBuilder parameterBuilder;
    uri = new Uri("  /\\\u00a0");
    parameterBuilder = this.Constructor(uri);
    PexAssert.IsNotNull((object)parameterBuilder);
}
[Test]
[PexGeneratedBy(typeof(ParameterBuilderTests))]
public void Constructor85103()
{
    Uri uri;
    ParameterBuilder parameterBuilder;
    uri = new Uri("  aa:");
    parameterBuilder = this.Constructor(uri);
    PexAssert.IsNotNull((object)parameterBuilder);
}
	}
}
