// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using System.Linq.Expressions;
using NUnit.Framework;
using Microsoft.Pex.Framework.Moles;
using Linq2Rest.Provider.Moles;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.Exceptions;

namespace Linq2Rest.Provider
{
	public partial class RestQueryableTTests
	{
[Test]
[PexGeneratedBy(typeof(RestQueryableTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void Constructor01ThrowsArgumentNullException155()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      RestQueryable<int> restQueryable;
      restQueryable = this.Constructor01<int>
                          ((IRestClient)null, (ISerializerFactory)null, (Expression)null);
      disposables.Add((IDisposable)restQueryable);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(RestQueryableTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void Constructor01ThrowsArgumentNullException154()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      using (PexDisposableContext disposables = PexDisposableContext.Create())
      {
        SIRestClient sIRestClient;
        RestQueryable<int> restQueryable;
        sIRestClient = new SIRestClient();
        disposables.Add((IDisposable)sIRestClient);
        restQueryable = this.Constructor01<int>
                            ((IRestClient)sIRestClient, (ISerializerFactory)null, (Expression)null);
        disposables.Add((IDisposable)restQueryable);
        disposables.Dispose();
      }
    }
}
[Test]
[PexGeneratedBy(typeof(RestQueryableTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void Constructor01ThrowsArgumentNullException951()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      using (PexDisposableContext disposables = PexDisposableContext.Create())
      {
        SIRestClient sIRestClient;
        SISerializerFactory sISerializerFactory;
        RestQueryable<int> restQueryable;
        sIRestClient = new SIRestClient();
        disposables.Add((IDisposable)sIRestClient);
        sISerializerFactory = new SISerializerFactory();
        restQueryable = this.Constructor01<int>((IRestClient)sIRestClient, 
                                                (ISerializerFactory)sISerializerFactory, (Expression)null);
        disposables.Add((IDisposable)restQueryable);
        disposables.Dispose();
      }
    }
}
[Test]
[PexGeneratedBy(typeof(RestQueryableTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException29()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      RestQueryable<int> restQueryable;
      restQueryable =
        this.Constructor<int>((IRestClient)null, (ISerializerFactory)null);
      disposables.Add((IDisposable)restQueryable);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(RestQueryableTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException62()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      using (PexDisposableContext disposables = PexDisposableContext.Create())
      {
        SIRestClient sIRestClient;
        RestQueryable<int> restQueryable;
        sIRestClient = new SIRestClient();
        disposables.Add((IDisposable)sIRestClient);
        restQueryable =
          this.Constructor<int>((IRestClient)sIRestClient, (ISerializerFactory)null);
        disposables.Add((IDisposable)restQueryable);
        disposables.Dispose();
      }
    }
}
[Test]
[PexGeneratedBy(typeof(RestQueryableTTests))]
[Ignore("this test requires to run under the Pex profiler in order to reproduce")]
[PexRaisedException(typeof(PexRetryException))]
[PexNotReproducible]
public void ConstructorThrowsPexRetryException289()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      using (PexDisposableContext disposables = PexDisposableContext.Create())
      {
        SIRestClient sIRestClient;
        SISerializerFactory sISerializerFactory;
        Uri uri;
        RestQueryable<int> restQueryable;
        sIRestClient = new SIRestClient();
        disposables.Add((IDisposable)sIRestClient);
        sISerializerFactory = new SISerializerFactory();
        uri = new Uri("x:\\");
        IPexChoiceRecorder choices = PexChoose.Replay.Setup();
        choices.NextSegment(3).DefaultSession
            .At(0, "sIRestClient.Linq2Rest.Provider.IRestClient.get_ServiceBase", 
                                                 (object)uri);
        restQueryable = this.Constructor<int>
                            ((IRestClient)sIRestClient, (ISerializerFactory)sISerializerFactory);
        disposables.Add((IDisposable)restQueryable);
        disposables.Dispose();
      }
    }
}
	}
}
