// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Moles;
using Microsoft.Pex.Framework.Generated;
using Linq2Rest.Provider.Moles;
using System.Linq;
using Microsoft.Pex.Framework.Explorable;
using System.Collections.Generic;
using System.Linq.Expressions;
using NUnit.Framework;

namespace Linq2Rest.Provider
{
	public partial class RestContextTTests
	{
	}
}
