// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using NUnit.Framework;
using Microsoft.Pex.Framework.Moles;
using Linq2Rest.Provider.Moles;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.Exceptions;

namespace Linq2Rest.Provider
{
	public partial class RestQueryProviderTTests
	{
[Test]
[PexGeneratedBy(typeof(RestQueryProviderTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void Constructor01ThrowsArgumentNullException322()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      RestQueryProvider<int> restQueryProvider;
      restQueryProvider = this.Constructor01<int>
                              ((IRestClient)null, (ISerializerFactory)null, (IExpressionProcessor)null);
      disposables.Add((IDisposable)restQueryProvider);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(RestQueryProviderTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void Constructor01ThrowsArgumentNullException678()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      using (PexDisposableContext disposables = PexDisposableContext.Create())
      {
        SIRestClient sIRestClient;
        RestQueryProvider<int> restQueryProvider;
        sIRestClient = new SIRestClient();
        disposables.Add((IDisposable)sIRestClient);
        restQueryProvider = this.Constructor01<int>((IRestClient)sIRestClient, 
                                                    (ISerializerFactory)null, (IExpressionProcessor)null);
        disposables.Add((IDisposable)restQueryProvider);
        disposables.Dispose();
      }
    }
}
[Test]
[PexGeneratedBy(typeof(RestQueryProviderTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void Constructor01ThrowsArgumentNullException750()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      using (PexDisposableContext disposables = PexDisposableContext.Create())
      {
        SIRestClient sIRestClient;
        SISerializerFactory sISerializerFactory;
        RestQueryProvider<int> restQueryProvider;
        sIRestClient = new SIRestClient();
        disposables.Add((IDisposable)sIRestClient);
        sISerializerFactory = new SISerializerFactory();
        restQueryProvider = this.Constructor01<int>((IRestClient)sIRestClient, 
                                                    (ISerializerFactory)sISerializerFactory, (IExpressionProcessor)null);
        disposables.Add((IDisposable)restQueryProvider);
        disposables.Dispose();
      }
    }
}
[Test]
[PexGeneratedBy(typeof(RestQueryProviderTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException662()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      RestQueryProvider<int> restQueryProvider;
      restQueryProvider =
        this.Constructor<int>((IRestClient)null, (ISerializerFactory)null);
      disposables.Add((IDisposable)restQueryProvider);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(RestQueryProviderTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException86()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      using (PexDisposableContext disposables = PexDisposableContext.Create())
      {
        SIRestClient sIRestClient;
        RestQueryProvider<int> restQueryProvider;
        sIRestClient = new SIRestClient();
        disposables.Add((IDisposable)sIRestClient);
        restQueryProvider =
          this.Constructor<int>((IRestClient)sIRestClient, (ISerializerFactory)null);
        disposables.Add((IDisposable)restQueryProvider);
        disposables.Dispose();
      }
    }
}
[Test]
[PexGeneratedBy(typeof(RestQueryProviderTTests))]
[Ignore("this test requires to run under the Pex profiler in order to reproduce")]
[PexRaisedException(typeof(PexRetryException))]
[PexNotReproducible]
public void ConstructorThrowsPexRetryException643()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      using (PexDisposableContext disposables = PexDisposableContext.Create())
      {
        SIRestClient sIRestClient;
        SISerializerFactory sISerializerFactory;
        Uri uri;
        RestQueryProvider<int> restQueryProvider;
        sIRestClient = new SIRestClient();
        disposables.Add((IDisposable)sIRestClient);
        sISerializerFactory = new SISerializerFactory();
        uri = new Uri("  \\/-");
        IPexChoiceRecorder choices = PexChoose.Replay.Setup();
        choices.NextSegment(3).DefaultSession
            .At(0, "sIRestClient.Linq2Rest.Provider.IRestClient.get_ServiceBase", 
                                                 (object)uri);
        restQueryProvider = this.Constructor<int>
                                ((IRestClient)sIRestClient, (ISerializerFactory)sISerializerFactory);
        disposables.Add((IDisposable)restQueryProvider);
        disposables.Dispose();
      }
    }
}
[Test]
[PexGeneratedBy(typeof(RestQueryProviderTTests))]
[Ignore("this test requires to run under the Pex profiler in order to reproduce")]
[PexRaisedException(typeof(PexRetryException))]
[PexNotReproducible]
public void ConstructorThrowsPexRetryException928()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      using (PexDisposableContext disposables = PexDisposableContext.Create())
      {
        SIRestClient sIRestClient;
        SISerializerFactory sISerializerFactory;
        Uri uri;
        RestQueryProvider<int> restQueryProvider;
        sIRestClient = new SIRestClient();
        disposables.Add((IDisposable)sIRestClient);
        sISerializerFactory = new SISerializerFactory();
        uri = new Uri("  /\\\u00a1");
        IPexChoiceRecorder choices = PexChoose.Replay.Setup();
        choices.NextSegment(3).DefaultSession
            .At(0, "sIRestClient.Linq2Rest.Provider.IRestClient.get_ServiceBase", 
                                                 (object)uri);
        restQueryProvider = this.Constructor<int>
                                ((IRestClient)sIRestClient, (ISerializerFactory)sISerializerFactory);
        disposables.Add((IDisposable)restQueryProvider);
        disposables.Dispose();
      }
    }
}
	}
}
