// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using NUnit.Framework;
using Microsoft.Pex.Framework.Moles;
using Linq2Rest.Provider.Moles;
using Microsoft.Pex.Framework;

namespace Linq2Rest.Provider
{
	public partial class RestContextTTests
	{
[Test]
[PexGeneratedBy(typeof(RestContextTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException890()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      RestContext<int> restContext;
      restContext =
        this.Constructor<int>((IRestClient)null, (ISerializerFactory)null);
      disposables.Add((IDisposable)restContext);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(RestContextTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException291()
{
    using (PexChooseBehavedBehavior.Setup())
    {
      using (PexDisposableContext disposables = PexDisposableContext.Create())
      {
        SIRestClient sIRestClient;
        RestContext<int> restContext;
        sIRestClient = new SIRestClient();
        disposables.Add((IDisposable)sIRestClient);
        restContext =
          this.Constructor<int>((IRestClient)sIRestClient, (ISerializerFactory)null);
        disposables.Add((IDisposable)restContext);
        disposables.Dispose();
      }
    }
}
	}
}
