// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Linq.Expressions;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework;

namespace Linq2Rest.Parser.Readers
{
	public partial class DateTimeExpressionFactoryTests
	{
[Test]
[PexGeneratedBy(typeof(DateTimeExpressionFactoryTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConvertThrowsContractException143()
{
    try
    {
      ConstantExpression constantExpression;
      DateTimeExpressionFactory s0 = new DateTimeExpressionFactory();
      constantExpression = this.Convert(s0, (string)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(DateTimeExpressionFactoryTests))]
public void Convert454()
{
    ConstantExpression constantExpression;
    DateTimeExpressionFactory s0 = new DateTimeExpressionFactory();
    constantExpression = this.Convert(s0, "");
    PexAssert.IsNotNull((object)constantExpression);
    PexAssert.AreEqual<ExpressionType>
        (ExpressionType.Constant, constantExpression.NodeType);
    PexAssert.IsNotNull(constantExpression.Value);
    PexAssert.AreEqual<int>(1, ((DateTime)(constantExpression.Value)).Day);
    PexAssert.AreEqual<int>(0, ((DateTime)(constantExpression.Value)).Hour);
    PexAssert.AreEqual<int>(0, ((DateTime)(constantExpression.Value)).Minute);
    PexAssert.AreEqual<int>(0, ((DateTime)(constantExpression.Value)).Second);
    PexAssert.AreEqual<int>(1, ((DateTime)(constantExpression.Value)).Month);
    PexAssert.AreEqual<int>(1, ((DateTime)(constantExpression.Value)).Year);
    PexAssert.AreEqual<DayOfWeek>
        (DayOfWeek.Monday, ((DateTime)(constantExpression.Value)).DayOfWeek);
    PexAssert.AreEqual<int>(1, ((DateTime)(constantExpression.Value)).DayOfYear);
    PexAssert.AreEqual<DateTimeKind>
        (DateTimeKind.Unspecified, ((DateTime)(constantExpression.Value)).Kind);
    PexAssert.AreEqual<int>(0, ((DateTime)(constantExpression.Value)).Millisecond);
    PexAssert.IsNotNull((object)s0);
}
[Test]
[PexGeneratedBy(typeof(DateTimeExpressionFactoryTests))]
public void Convert414()
{
    ConstantExpression constantExpression;
    DateTimeExpressionFactory s0 = new DateTimeExpressionFactory();
    constantExpression = this.Convert(s0, "\0\0\0\0\0\0\0\0");
    PexAssert.IsNotNull((object)constantExpression);
    PexAssert.AreEqual<ExpressionType>
        (ExpressionType.Constant, constantExpression.NodeType);
    PexAssert.IsNotNull(constantExpression.Value);
    PexAssert.AreEqual<int>(1, ((DateTime)(constantExpression.Value)).Day);
    PexAssert.AreEqual<int>(0, ((DateTime)(constantExpression.Value)).Hour);
    PexAssert.AreEqual<int>(0, ((DateTime)(constantExpression.Value)).Minute);
    PexAssert.AreEqual<int>(0, ((DateTime)(constantExpression.Value)).Second);
    PexAssert.AreEqual<int>(1, ((DateTime)(constantExpression.Value)).Month);
    PexAssert.AreEqual<int>(1, ((DateTime)(constantExpression.Value)).Year);
    PexAssert.AreEqual<DayOfWeek>
        (DayOfWeek.Monday, ((DateTime)(constantExpression.Value)).DayOfWeek);
    PexAssert.AreEqual<int>(1, ((DateTime)(constantExpression.Value)).DayOfYear);
    PexAssert.AreEqual<DateTimeKind>
        (DateTimeKind.Unspecified, ((DateTime)(constantExpression.Value)).Kind);
    PexAssert.AreEqual<int>(0, ((DateTime)(constantExpression.Value)).Millisecond);
    PexAssert.IsNotNull((object)s0);
}
	}
}
