// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Linq.Expressions;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Linq2Rest.Parser.Readers
{
	public partial class ParameterValueReaderTests
	{
[Test]
[PexGeneratedBy(typeof(ParameterValueReaderTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ReadThrowsContractException664()
{
    try
    {
      Expression expression;
      expression = this.Read((Type)null, (string)null, (IFormatProvider)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(ParameterValueReaderTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ReadThrowsContractException872()
{
    try
    {
      Expression expression;
      expression = this.Read((Type)null, "", (IFormatProvider)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
	}
}
