// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace Linq2Rest
{
	public partial class GeneralExtensionsTests
	{
[Test]
[PexGeneratedBy(typeof(GeneralExtensionsTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void IsAnonymousTypeThrowsArgumentNullException106()
{
    bool b;
    b = this.IsAnonymousType((Type)null);
}
	}
}
