// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using System.IO;
using Microsoft.Pex.Framework;
using NUnit.Framework;

namespace Linq2Rest
{
	public partial class GeneralExtensionsTests
	{
[Test]
[PexGeneratedBy(typeof(GeneralExtensionsTests))]
public void ToStream24()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Stream stream;
      stream = this.ToStream((string)null);
      disposables.Add((IDisposable)stream);
      disposables.Dispose();
      PexAssert.IsNotNull((object)stream);
    }
}
[Test]
[PexGeneratedBy(typeof(GeneralExtensionsTests))]
public void ToStream101()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Stream stream;
      stream = this.ToStream(new string('\0', 15));
      disposables.Add((IDisposable)stream);
      disposables.Dispose();
      PexAssert.IsNotNull((object)stream);
    }
}
[Test]
[PexGeneratedBy(typeof(GeneralExtensionsTests))]
public void ToStream757()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Stream stream;
      stream = this.ToStream("\udc00");
      disposables.Add((IDisposable)stream);
      disposables.Dispose();
      PexAssert.IsNotNull((object)stream);
    }
}
[Test]
[PexGeneratedBy(typeof(GeneralExtensionsTests))]
public void ToStream2401()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Stream stream;
      stream = this.ToStream("\ud801\0\0");
      disposables.Add((IDisposable)stream);
      disposables.Dispose();
      PexAssert.IsNotNull((object)stream);
    }
}
	}
}
