// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Linq2Rest
{
	public partial class MethodProviderTests
	{
[Test]
[PexGeneratedBy(typeof(MethodProviderTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void GetIEnumerableImplThrowsContractException625()
{
    try
    {
      Type type;
      type = this.GetIEnumerableImpl((Type)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
	}
}
