// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Linq.Expressions;
using Linq2Rest.Parser;
using System.Collections.Generic;
using Microsoft.Pex.Framework;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace Linq2Rest
{
	public partial class ModelFilterTTests
	{
[Test]
[PexGeneratedBy(typeof(ModelFilterTTests))]
public void Constructor258()
{
    ModelFilter<int> modelFilter;
    modelFilter = this.Constructor<int>
                      ((Expression<Func<int, bool>>)null, (Expression<Func<int, object>>)null, 
                       (IEnumerable<SortDescription<int>>)null, 0, 0);
    PexAssert.IsNotNull((object)modelFilter);
}
	}
}
