// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Linq2Rest.Parser.Moles;
using Linq2Rest.Parser;
using System.Reflection;
using System.Collections.Generic;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace Linq2Rest
{
	public partial class RuntimeTypeProviderTests
	{
[Test]
[PexGeneratedBy(typeof(RuntimeTypeProviderTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void GetThrowsArgumentNullException643()
{
    SIMemberNameResolver sIMemberNameResolver;
    RuntimeTypeProvider runtimeTypeProvider;
    Type type;
    sIMemberNameResolver = new SIMemberNameResolver();
    runtimeTypeProvider =
      new RuntimeTypeProvider((IMemberNameResolver)sIMemberNameResolver);
    type = this.Get(runtimeTypeProvider, (Type)null, (IEnumerable<MemberInfo>)null);
}
	}
}
