// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework;

namespace Linq2Rest.Reactive.Implementations
{
	public partial class AsyncJsonRestClientFactoryTests
	{
[Test]
[PexGeneratedBy(typeof(AsyncJsonRestClientFactoryTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException787()
{
    AsyncJsonRestClientFactory asyncJsonRestClientFactory;
    asyncJsonRestClientFactory = this.Constructor((Uri)null);
}
[Test]
[PexGeneratedBy(typeof(AsyncJsonRestClientFactoryTests))]
[Ignore("the test state was: path bounds exceeded")]
public void Constructor01()
{
    Uri uri;
    AsyncJsonRestClientFactory asyncJsonRestClientFactory;
    uri = new Uri("\u0100");
    asyncJsonRestClientFactory = this.Constructor(uri);
}
[Test]
[PexGeneratedBy(typeof(AsyncJsonRestClientFactoryTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException392()
{
    Uri uri;
    AsyncJsonRestClientFactory asyncJsonRestClientFactory;
    uri = new Uri("D:\\");
    asyncJsonRestClientFactory = this.Constructor(uri);
}
[Test]
[PexGeneratedBy(typeof(AsyncJsonRestClientFactoryTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException535()
{
    Uri uri;
    AsyncJsonRestClientFactory asyncJsonRestClientFactory;
    uri = new Uri("/\\0");
    asyncJsonRestClientFactory = this.Constructor(uri);
}
[Test]
[PexGeneratedBy(typeof(AsyncJsonRestClientFactoryTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException657()
{
    Uri uri;
    AsyncJsonRestClientFactory asyncJsonRestClientFactory;
    uri = new Uri("/\\a");
    asyncJsonRestClientFactory = this.Constructor(uri);
}
[Test]
[PexGeneratedBy(typeof(AsyncJsonRestClientFactoryTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException156()
{
    Uri uri;
    AsyncJsonRestClientFactory asyncJsonRestClientFactory;
    uri = new Uri("a0:");
    asyncJsonRestClientFactory = this.Constructor(uri);
}
[Test]
[PexGeneratedBy(typeof(AsyncJsonRestClientFactoryTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException262()
{
    Uri uri;
    AsyncJsonRestClientFactory asyncJsonRestClientFactory;
    uri = new Uri("aA:");
    asyncJsonRestClientFactory = this.Constructor(uri);
}
[Test]
[PexGeneratedBy(typeof(AsyncJsonRestClientFactoryTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException739()
{
    Uri uri;
    AsyncJsonRestClientFactory asyncJsonRestClientFactory;
    uri = new Uri("/\\-");
    asyncJsonRestClientFactory = this.Constructor(uri);
}
[Test]
[PexGeneratedBy(typeof(AsyncJsonRestClientFactoryTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException810()
{
    Uri uri;
    AsyncJsonRestClientFactory asyncJsonRestClientFactory;
    uri = new Uri("/\\\u00a1");
    asyncJsonRestClientFactory = this.Constructor(uri);
}
[Test]
[PexGeneratedBy(typeof(AsyncJsonRestClientFactoryTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException239()
{
    Uri uri;
    AsyncJsonRestClientFactory asyncJsonRestClientFactory;
    uri = new Uri("a+:/\\#");
    asyncJsonRestClientFactory = this.Constructor(uri);
}
[Test]
[PexGeneratedBy(typeof(AsyncJsonRestClientFactoryTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException170()
{
    Uri uri;
    AsyncJsonRestClientFactory asyncJsonRestClientFactory;
    uri = new Uri("//0-");
    asyncJsonRestClientFactory = this.Constructor(uri);
}
[Test]
[PexGeneratedBy(typeof(AsyncJsonRestClientFactoryTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException290()
{
    Uri uri;
    AsyncJsonRestClientFactory asyncJsonRestClientFactory;
    uri = new Uri("//1\\");
    asyncJsonRestClientFactory = this.Constructor(uri);
}
	}
}
