// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework;

namespace Linq2Rest.Provider.Writers
{
	public partial class BooleanValueWriterTests
	{
[Test]
[PexGeneratedBy(typeof(BooleanValueWriterTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void WriteThrowsContractException230()
{
    try
    {
      string s;
      BooleanValueWriter s0 = new BooleanValueWriter();
      s = this.Write(s0, (object)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(BooleanValueWriterTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void WriteThrowsContractException910()
{
    try
    {
      string s;
      BooleanValueWriter s0 = new BooleanValueWriter();
      object s1 = new object();
      s = this.Write(s0, s1);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(BooleanValueWriterTests))]
public void Write999()
{
    string s;
    BooleanValueWriter s0 = new BooleanValueWriter();
    object boxb = (object)(default(bool));
    s = this.Write(s0, boxb);
    PexAssert.AreEqual<string>("false", s);
    PexAssert.IsNotNull((object)s0);
}
[Test]
[PexGeneratedBy(typeof(BooleanValueWriterTests))]
public void Write138()
{
    string s;
    BooleanValueWriter s0 = new BooleanValueWriter();
    object boxb = (object)(default(bool));
    PexSafeHelpers.AssignBoxedValue<bool>(boxb, true);
    s = this.Write(s0, boxb);
    PexAssert.AreEqual<string>("true", s);
    PexAssert.IsNotNull((object)s0);
}
	}
}
