// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework;

namespace Linq2Rest.Provider.Writers
{
	public partial class ByteArrayValueWriterTests
	{
[Test]
[PexGeneratedBy(typeof(ByteArrayValueWriterTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void WriteThrowsContractException240()
{
    try
    {
      string s;
      ByteArrayValueWriter s0 = new ByteArrayValueWriter();
      s = this.Write(s0, (object)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(ByteArrayValueWriterTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void WriteThrowsContractException526()
{
    try
    {
      string s;
      ByteArrayValueWriter s0 = new ByteArrayValueWriter();
      object s1 = new object();
      s = this.Write(s0, s1);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(ByteArrayValueWriterTests))]
public void Write459()
{
    string s;
    ByteArrayValueWriter s0 = new ByteArrayValueWriter();
    byte[] bs = new byte[0];
    s = this.Write(s0, (object)bs);
    PexAssert.AreEqual<string>("X\'\'", s);
    PexAssert.IsNotNull((object)s0);
}
[Test]
[PexGeneratedBy(typeof(ByteArrayValueWriterTests))]
public void Write918()
{
    string s;
    ByteArrayValueWriter s0 = new ByteArrayValueWriter();
    byte[] bs = new byte[1];
    s = this.Write(s0, (object)bs);
    PexAssert.AreEqual<string>("X\'AA==\'", s);
    PexAssert.IsNotNull((object)s0);
}
[Test]
[PexGeneratedBy(typeof(ByteArrayValueWriterTests))]
public void Write169()
{
    string s;
    ByteArrayValueWriter s0 = new ByteArrayValueWriter();
    byte[] bs = new byte[3];
    s = this.Write(s0, (object)bs);
    PexAssert.AreEqual<string>("X\'AAAA\'", s);
    PexAssert.IsNotNull((object)s0);
}
[Test]
[PexGeneratedBy(typeof(ByteArrayValueWriterTests))]
[Ignore("the test state was: path bounds exceeded")]
public void Write248()
{
    string s;
    ByteArrayValueWriter s0 = new ByteArrayValueWriter();
    byte[] bs = new byte[1662];
    s = this.Write(s0, (object)bs);
}
	}
}
