// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework;

namespace Linq2Rest.Provider.Writers
{
	public partial class ByteValueWriterTests
	{
[Test]
[PexGeneratedBy(typeof(ByteValueWriterTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void WriteThrowsContractException317()
{
    try
    {
      string s;
      ByteValueWriter s0 = new ByteValueWriter();
      s = this.Write(s0, (object)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(ByteValueWriterTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void WriteThrowsContractException232()
{
    try
    {
      string s;
      ByteValueWriter s0 = new ByteValueWriter();
      object s1 = new object();
      s = this.Write(s0, s1);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(ByteValueWriterTests))]
public void Write118()
{
    string s;
    ByteValueWriter s0 = new ByteValueWriter();
    object boxb = (object)(default(byte));
    s = this.Write(s0, boxb);
    PexAssert.AreEqual<string>("0", s);
    PexAssert.IsNotNull((object)s0);
}
[Test]
[PexGeneratedBy(typeof(ByteValueWriterTests))]
public void Write262()
{
    string s;
    ByteValueWriter s0 = new ByteValueWriter();
    object boxb = (object)(default(byte));
    PexSafeHelpers.AssignBoxedValue<byte>(boxb, (byte)1);
    s = this.Write(s0, boxb);
    PexAssert.AreEqual<string>("1", s);
    PexAssert.IsNotNull((object)s0);
}
	}
}
