// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace Linq2Rest.Provider.Writers
{
	public partial class IntegerValueWriterTests
	{
[Test]
[PexGeneratedBy(typeof(IntegerValueWriterTests))]
public void HandlesGet351()
{
    Type type;
    UnsignedLongValueWriter s0 = new UnsignedLongValueWriter();
    type = this.HandlesGet((IntegerValueWriter)s0);
    PexAssert.IsNotNull((object)type);
}
[Test]
[PexGeneratedBy(typeof(IntegerValueWriterTests))]
public void HandlesGet729()
{
    Type type;
    UnsignedShortValueWriter s0 = new UnsignedShortValueWriter();
    type = this.HandlesGet((IntegerValueWriter)s0);
    PexAssert.IsNotNull((object)type);
}
[Test]
[PexGeneratedBy(typeof(IntegerValueWriterTests))]
public void HandlesGet932()
{
    Type type;
    LongValueWriter s0 = new LongValueWriter();
    type = this.HandlesGet((IntegerValueWriter)s0);
    PexAssert.IsNotNull((object)type);
}
[Test]
[PexGeneratedBy(typeof(IntegerValueWriterTests))]
public void HandlesGet595()
{
    Type type;
    ShortValueWriter s0 = new ShortValueWriter();
    type = this.HandlesGet((IntegerValueWriter)s0);
    PexAssert.IsNotNull((object)type);
}
[Test]
[PexGeneratedBy(typeof(IntegerValueWriterTests))]
public void HandlesGet286()
{
    Type type;
    IntValueWriter s0 = new IntValueWriter();
    type = this.HandlesGet((IntegerValueWriter)s0);
    PexAssert.IsNotNull((object)type);
}
[Test]
[PexGeneratedBy(typeof(IntegerValueWriterTests))]
public void HandlesGet414()
{
    Type type;
    UnsignedIntValueWriter s0 = new UnsignedIntValueWriter();
    type = this.HandlesGet((IntegerValueWriter)s0);
    PexAssert.IsNotNull((object)type);
}
	}
}
