// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework;

namespace Linq2Rest.Provider.Writers
{
	public partial class RationalValueWriterTests
	{
[Test]
[PexGeneratedBy(typeof(RationalValueWriterTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void WriteThrowsContractException286()
{
    try
    {
      string s;
      DecimalValueWriter s0 = new DecimalValueWriter();
      s = this.Write((RationalValueWriter)s0, (object)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(RationalValueWriterTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void WriteThrowsContractException444()
{
    try
    {
      string s;
      DecimalValueWriter s0 = new DecimalValueWriter();
      object s1 = new object();
      s = this.Write((RationalValueWriter)s0, s1);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(RationalValueWriterTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void WriteThrowsContractException167()
{
    try
    {
      string s;
      SingleValueWriter s0 = new SingleValueWriter();
      object s1 = new object();
      s = this.Write((RationalValueWriter)s0, s1);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(RationalValueWriterTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void WriteThrowsContractException170()
{
    try
    {
      string s;
      DoubleValueWriter s0 = new DoubleValueWriter();
      object s1 = new object();
      s = this.Write((RationalValueWriter)s0, s1);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(RationalValueWriterTests))]
public void Write770()
{
    string s;
    DecimalValueWriter s0 = new DecimalValueWriter();
    object box = (object)(default(decimal));
    s = this.Write((RationalValueWriter)s0, box);
    PexAssert.AreEqual<string>("0", s);
}
	}
}
