// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Linq2Rest.Provider;
using Microsoft.Pex.Framework;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Linq2Rest.Reactive
{
	public partial class AsyncExpressionProcessorTests
	{
[Test]
[PexGeneratedBy(typeof(AsyncExpressionProcessorTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException626()
{
    try
    {
      AsyncExpressionProcessor asyncExpressionProcessor;
      asyncExpressionProcessor = this.Constructor((IExpressionWriter)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(AsyncExpressionProcessorTests))]
public void Constructor928()
{
    AsyncExpressionProcessor asyncExpressionProcessor;
    ExpressionWriter s0 = new ExpressionWriter();
    asyncExpressionProcessor = this.Constructor((IExpressionWriter)s0);
    PexAssert.IsNotNull((object)asyncExpressionProcessor);
}
	}
}
