// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Linq2Rest.Provider;
using System.Linq.Expressions;
using System.Collections.Generic;
using System.Collections;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework;
using Microsoft.Pex.Engine.Exceptions;
using Microsoft.Pex.Framework.Explorable;

namespace Linq2Rest.Reactive
{
	public partial class AsyncExpressionProcessorTests
	{
[Test]
[PexGeneratedBy(typeof(AsyncExpressionProcessorTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ProcessMethodCallThrowsContractException967()
{
    try
    {
      AsyncExpressionProcessor asyncExpressionProcessor;
      IObservable<int> iObservable;
      ExpressionWriter s0 = new ExpressionWriter();
      asyncExpressionProcessor =
        new AsyncExpressionProcessor((IExpressionWriter)s0);
      iObservable = this.ProcessMethodCall<int>
                        (asyncExpressionProcessor, (MethodCallExpression)null, 
                         (ParameterBuilder)null, 
                         (Func<ParameterBuilder, IObservable<IEnumerable<int>>>)null, 
                         (Func<Type, ParameterBuilder, IObservable<IEnumerable>>)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
	}
}
