// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;

namespace Linq2Rest.Reactive
{
	public partial class InteralObservableExtensionsTests
	{
[Test]
[PexGeneratedBy(typeof(InteralObservableExtensionsTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ToQbservableThrowsContractException124()
{
    try
    {
      object o;
      o = this.ToQbservable((IEnumerable)null, (Type)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(InteralObservableExtensionsTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ToQbservableThrowsContractException792()
{
    try
    {
      object o;
      object[] os = new object[0];
      o = this.ToQbservable((IEnumerable)os, (Type)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
	}
}
