// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Linq2Rest.Provider;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Linq2Rest.Reactive.Moles;
using Linq2Rest.Implementations;
using Microsoft.Pex.Framework.Explorable;
using System.Collections.Generic;
using Microsoft.Pex.Framework;

namespace Linq2Rest.Reactive
{
	public partial class RestObservableTTests
	{
[Test]
[PexGeneratedBy(typeof(RestObservableTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException404()
{
    RestObservable<int> restObservable;
    restObservable =
      this.Constructor<int>((IAsyncRestClientFactory)null, (ISerializerFactory)null);
}
[Test]
[PexGeneratedBy(typeof(RestObservableTTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException214()
{
    SIAsyncRestClientFactory sIAsyncRestClientFactory;
    RestObservable<int> restObservable;
    sIAsyncRestClientFactory = new SIAsyncRestClientFactory();
    restObservable =
      this.Constructor<int>((IAsyncRestClientFactory)sIAsyncRestClientFactory, 
                            (ISerializerFactory)null);
}
[Test]
[PexGeneratedBy(typeof(RestObservableTTests))]
public void Constructor643()
{
    SIAsyncRestClientFactory sIAsyncRestClientFactory;
    XmlDataContractSerializerFactory xmlDataContractSerializerFactory;
    RestObservable<int> restObservable;
    sIAsyncRestClientFactory = new SIAsyncRestClientFactory();
    Type[] types = new Type[0];
    xmlDataContractSerializerFactory =
      PexInvariant.CreateInstance<XmlDataContractSerializerFactory>();
    PexInvariant.SetField<IEnumerable<Type>>
        ((object)xmlDataContractSerializerFactory, 
         "_knownTypes", (IEnumerable<Type>)types);
    PexInvariant.CheckInvariant((object)xmlDataContractSerializerFactory);
    restObservable =
      this.Constructor<int>((IAsyncRestClientFactory)sIAsyncRestClientFactory, 
                            (ISerializerFactory)xmlDataContractSerializerFactory);
    PexAssert.IsNotNull((object)restObservable);
}
[Test]
[PexGeneratedBy(typeof(RestObservableTTests))]
public void Constructor64301()
{
    SIAsyncRestClientFactory sIAsyncRestClientFactory;
    XmlSerializerFactory xmlSerializerFactory;
    RestObservable<int> restObservable;
    sIAsyncRestClientFactory = new SIAsyncRestClientFactory();
    Type[] types = new Type[0];
    xmlSerializerFactory = PexInvariant.CreateInstance<XmlSerializerFactory>();
    PexInvariant.SetField<IEnumerable<Type>>
        ((object)xmlSerializerFactory, "_knownTypes", (IEnumerable<Type>)types);
    PexInvariant.CheckInvariant((object)xmlSerializerFactory);
    restObservable =
      this.Constructor<int>((IAsyncRestClientFactory)sIAsyncRestClientFactory, 
                            (ISerializerFactory)xmlSerializerFactory);
    PexAssert.IsNotNull((object)restObservable);
}
[Test]
[PexGeneratedBy(typeof(RestObservableTTests))]
public void Constructor64302()
{
    SIAsyncRestClientFactory sIAsyncRestClientFactory;
    JsonDataContractSerializerFactory jsonDataContractSerializerFactory;
    RestObservable<int> restObservable;
    sIAsyncRestClientFactory = new SIAsyncRestClientFactory();
    Type[] types = new Type[0];
    jsonDataContractSerializerFactory =
      PexInvariant.CreateInstance<JsonDataContractSerializerFactory>();
    PexInvariant.SetField<IEnumerable<Type>>
        ((object)jsonDataContractSerializerFactory, 
         "_knownTypes", (IEnumerable<Type>)types);
    PexInvariant.CheckInvariant((object)jsonDataContractSerializerFactory);
    restObservable =
      this.Constructor<int>((IAsyncRestClientFactory)sIAsyncRestClientFactory, 
                            (ISerializerFactory)jsonDataContractSerializerFactory);
    PexAssert.IsNotNull((object)restObservable);
}
	}
}
