// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Reactive;
using Linq2Rest.Provider;
using System.Linq.Expressions;
using System.Reactive.Concurrency;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Engine.Exceptions;
using Linq2Rest.Reactive.Moles;
using Linq2Rest.Implementations;
using Microsoft.Pex.Framework.Explorable;
using System.Collections.Generic;

namespace Linq2Rest.Reactive
{
	public partial class TriggeredRestObservableTTests
	{
[Test]
[PexGeneratedBy(typeof(TriggeredRestObservableTTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException455()
{
    try
    {
      TriggeredRestObservable<int> triggeredRestObservable;
      triggeredRestObservable = this.Constructor<int>((IObservable<Unit>)null, 
                                                      (IAsyncRestClientFactory)null, (ISerializerFactory)null, 
                                                      (Expression)null, (IScheduler)null, (IScheduler)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(TriggeredRestObservableTTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException111()
{
    try
    {
      SIAsyncRestClientFactory sIAsyncRestClientFactory;
      TriggeredRestObservable<int> triggeredRestObservable;
      sIAsyncRestClientFactory = new SIAsyncRestClientFactory();
      triggeredRestObservable = this.Constructor<int>((IObservable<Unit>)null, 
                                                      (IAsyncRestClientFactory)sIAsyncRestClientFactory, 
                                                      (ISerializerFactory)null, 
                                                      (Expression)null, (IScheduler)null, (IScheduler)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(TriggeredRestObservableTTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException716()
{
    try
    {
      SIAsyncRestClientFactory sIAsyncRestClientFactory;
      XmlSerializerFactory xmlSerializerFactory;
      TriggeredRestObservable<int> triggeredRestObservable;
      sIAsyncRestClientFactory = new SIAsyncRestClientFactory();
      Type[] types = new Type[0];
      xmlSerializerFactory = PexInvariant.CreateInstance<XmlSerializerFactory>();
      PexInvariant.SetField<IEnumerable<Type>>
          ((object)xmlSerializerFactory, "_knownTypes", (IEnumerable<Type>)types);
      PexInvariant.CheckInvariant((object)xmlSerializerFactory);
      triggeredRestObservable = this.Constructor<int>((IObservable<Unit>)null, 
                                                      (IAsyncRestClientFactory)sIAsyncRestClientFactory, 
                                                      (ISerializerFactory)xmlSerializerFactory, 
                                                      (Expression)null, (IScheduler)null, (IScheduler)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(TriggeredRestObservableTTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException649()
{
    try
    {
      SIAsyncRestClientFactory sIAsyncRestClientFactory;
      JsonDataContractSerializerFactory jsonDataContractSerializerFactory;
      TriggeredRestObservable<int> triggeredRestObservable;
      sIAsyncRestClientFactory = new SIAsyncRestClientFactory();
      Type[] types = new Type[0];
      jsonDataContractSerializerFactory =
        PexInvariant.CreateInstance<JsonDataContractSerializerFactory>();
      PexInvariant.SetField<IEnumerable<Type>>
          ((object)jsonDataContractSerializerFactory, 
           "_knownTypes", (IEnumerable<Type>)types);
      PexInvariant.CheckInvariant((object)jsonDataContractSerializerFactory);
      triggeredRestObservable = this.Constructor<int>((IObservable<Unit>)null, 
                                                      (IAsyncRestClientFactory)sIAsyncRestClientFactory, 
                                                      (ISerializerFactory)jsonDataContractSerializerFactory, 
                                                      (Expression)null, (IScheduler)null, (IScheduler)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
[Test]
[PexGeneratedBy(typeof(TriggeredRestObservableTTests))]
[PexRaisedContractException(PexExceptionState.Expected)]
public void ConstructorThrowsContractException15()
{
    try
    {
      SIAsyncRestClientFactory sIAsyncRestClientFactory;
      XmlDataContractSerializerFactory xmlDataContractSerializerFactory;
      TriggeredRestObservable<int> triggeredRestObservable;
      sIAsyncRestClientFactory = new SIAsyncRestClientFactory();
      Type[] types = new Type[0];
      xmlDataContractSerializerFactory =
        PexInvariant.CreateInstance<XmlDataContractSerializerFactory>();
      PexInvariant.SetField<IEnumerable<Type>>
          ((object)xmlDataContractSerializerFactory, 
           "_knownTypes", (IEnumerable<Type>)types);
      PexInvariant.CheckInvariant((object)xmlDataContractSerializerFactory);
      triggeredRestObservable = this.Constructor<int>((IObservable<Unit>)null, 
                                                      (IAsyncRestClientFactory)sIAsyncRestClientFactory, 
                                                      (ISerializerFactory)xmlDataContractSerializerFactory, 
                                                      (Expression)null, (IScheduler)null, (IScheduler)null);
      throw 
        new AssertionException("expected an exception of type ContractException");
    }
    catch(Exception ex)
    {
      if (!PexContract.IsContractException(ex))
        throw ex;
    }
}
	}
}
