// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Linq2Rest.Provider;
using Microsoft.Pex.Framework.Explorable;
using System.Collections.Generic;
using Microsoft.Pex.Framework;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace Linq2Rest.Implementations
{
	public partial class JsonDataContractSerializerFactoryTests
	{
[Test]
[PexGeneratedBy(typeof(JsonDataContractSerializerFactoryTests))]
public void Create690()
{
    JsonDataContractSerializerFactory jsonDataContractSerializerFactory;
    ISerializer<int> iSerializer;
    Type[] types = new Type[0];
    jsonDataContractSerializerFactory =
      PexInvariant.CreateInstance<JsonDataContractSerializerFactory>();
    PexInvariant.SetField<IEnumerable<Type>>
        ((object)jsonDataContractSerializerFactory, 
         "_knownTypes", (IEnumerable<Type>)types);
    PexInvariant.CheckInvariant((object)jsonDataContractSerializerFactory);
    iSerializer = this.Create<int>(jsonDataContractSerializerFactory);
    PexAssert.IsNotNull((object)iSerializer);
    PexAssert.IsNotNull((object)jsonDataContractSerializerFactory);
}
[Test]
[PexGeneratedBy(typeof(JsonDataContractSerializerFactoryTests))]
public void Create69001()
{
    JsonDataContractSerializerFactory jsonDataContractSerializerFactory;
    ISerializer<int> iSerializer;
    Type[] types = new Type[1];
    jsonDataContractSerializerFactory =
      PexInvariant.CreateInstance<JsonDataContractSerializerFactory>();
    PexInvariant.SetField<IEnumerable<Type>>
        ((object)jsonDataContractSerializerFactory, 
         "_knownTypes", (IEnumerable<Type>)types);
    PexInvariant.CheckInvariant((object)jsonDataContractSerializerFactory);
    iSerializer = this.Create<int>(jsonDataContractSerializerFactory);
    PexAssert.IsNotNull((object)iSerializer);
    PexAssert.IsNotNull((object)jsonDataContractSerializerFactory);
}
[Test]
[PexGeneratedBy(typeof(JsonDataContractSerializerFactoryTests))]
[Ignore("the test state was: path bounds exceeded")]
public void Create770()
{
    JsonDataContractSerializerFactory jsonDataContractSerializerFactory;
    ISerializer<int> iSerializer;
    Type[] types = new Type[495];
    jsonDataContractSerializerFactory =
      PexInvariant.CreateInstance<JsonDataContractSerializerFactory>();
    PexInvariant.SetField<IEnumerable<Type>>
        ((object)jsonDataContractSerializerFactory, 
         "_knownTypes", (IEnumerable<Type>)types);
    PexInvariant.CheckInvariant((object)jsonDataContractSerializerFactory);
    iSerializer = this.Create<int>(jsonDataContractSerializerFactory);
}
	}
}
