// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework;
using NUnit.Framework;

namespace Linq2Rest.Implementations
{
	public partial class JsonRestClientTests
	{
[Test]
[PexGeneratedBy(typeof(JsonRestClientTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException333()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      JsonRestClient jsonRestClient;
      jsonRestClient = this.Constructor((Uri)null);
      disposables.Add((IDisposable)jsonRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(JsonRestClientTests))]
[Ignore("the test state was: path bounds exceeded")]
public void Constructor01()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      JsonRestClient jsonRestClient;
      uri = new Uri("\u0100");
      jsonRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)jsonRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(JsonRestClientTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException835()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      JsonRestClient jsonRestClient;
      uri = new Uri("D:\\");
      jsonRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)jsonRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(JsonRestClientTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException788()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      JsonRestClient jsonRestClient;
      uri = new Uri("/\\0");
      jsonRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)jsonRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(JsonRestClientTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException244()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      JsonRestClient jsonRestClient;
      uri = new Uri("/\\a");
      jsonRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)jsonRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(JsonRestClientTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException555()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      JsonRestClient jsonRestClient;
      uri = new Uri("a+:");
      jsonRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)jsonRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(JsonRestClientTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException171()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      JsonRestClient jsonRestClient;
      uri = new Uri("aa:");
      jsonRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)jsonRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(JsonRestClientTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException944()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      JsonRestClient jsonRestClient;
      uri = new Uri("/\\-");
      jsonRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)jsonRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(JsonRestClientTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException844()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      JsonRestClient jsonRestClient;
      uri = new Uri("a.:\\\\ ");
      jsonRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)jsonRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(JsonRestClientTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException755()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      JsonRestClient jsonRestClient;
      uri = new Uri("/\\\u00a1");
      jsonRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)jsonRestClient);
      disposables.Dispose();
    }
}
	}
}
