// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework.Explorable;
using Microsoft.Pex.Framework;
using NUnit.Framework;

namespace Linq2Rest.Implementations
{
	public partial class RestClientBaseTests
	{
[Test]
[PexGeneratedBy(typeof(RestClientBaseTests))]
public void Dispose395()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      RestClientBase restClientBase;
      restClientBase = PexInvariant.CreateInstance<RestClientBase>();
      PexInvariant.SetField<string>((object)restClientBase, "_acceptHeader", "");
      PexInvariant.SetField<Uri>
          ((object)restClientBase, "<ServiceBase>k__BackingField", (Uri)null);
      PexInvariant.CheckInvariant((object)restClientBase);
      disposables.Add((IDisposable)restClientBase);
      this.Dispose(restClientBase);
      disposables.Dispose();
      PexAssert.IsNotNull((object)restClientBase);
    }
}
	}
}
