// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Linq2Rest.Provider;
using Microsoft.Pex.Framework.Explorable;
using System.Collections.Generic;
using Microsoft.Pex.Framework;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace Linq2Rest.Implementations
{
	public partial class XmlDataContractSerializerFactoryTests
	{
[Test]
[PexGeneratedBy(typeof(XmlDataContractSerializerFactoryTests))]
public void Create670()
{
    XmlDataContractSerializerFactory xmlDataContractSerializerFactory;
    ISerializer<int> iSerializer;
    Type[] types = new Type[0];
    xmlDataContractSerializerFactory =
      PexInvariant.CreateInstance<XmlDataContractSerializerFactory>();
    PexInvariant.SetField<IEnumerable<Type>>
        ((object)xmlDataContractSerializerFactory, 
         "_knownTypes", (IEnumerable<Type>)types);
    PexInvariant.CheckInvariant((object)xmlDataContractSerializerFactory);
    iSerializer = this.Create<int>(xmlDataContractSerializerFactory);
    PexAssert.IsNotNull((object)iSerializer);
    PexAssert.IsNotNull((object)xmlDataContractSerializerFactory);
}
[Test]
[PexGeneratedBy(typeof(XmlDataContractSerializerFactoryTests))]
public void Create67001()
{
    XmlDataContractSerializerFactory xmlDataContractSerializerFactory;
    ISerializer<int> iSerializer;
    Type[] types = new Type[1];
    xmlDataContractSerializerFactory =
      PexInvariant.CreateInstance<XmlDataContractSerializerFactory>();
    PexInvariant.SetField<IEnumerable<Type>>
        ((object)xmlDataContractSerializerFactory, 
         "_knownTypes", (IEnumerable<Type>)types);
    PexInvariant.CheckInvariant((object)xmlDataContractSerializerFactory);
    iSerializer = this.Create<int>(xmlDataContractSerializerFactory);
    PexAssert.IsNotNull((object)iSerializer);
    PexAssert.IsNotNull((object)xmlDataContractSerializerFactory);
}
[Test]
[PexGeneratedBy(typeof(XmlDataContractSerializerFactoryTests))]
[Ignore("the test state was: path bounds exceeded")]
public void Create770()
{
    XmlDataContractSerializerFactory xmlDataContractSerializerFactory;
    ISerializer<int> iSerializer;
    Type[] types = new Type[495];
    xmlDataContractSerializerFactory =
      PexInvariant.CreateInstance<XmlDataContractSerializerFactory>();
    PexInvariant.SetField<IEnumerable<Type>>
        ((object)xmlDataContractSerializerFactory, 
         "_knownTypes", (IEnumerable<Type>)types);
    PexInvariant.CheckInvariant((object)xmlDataContractSerializerFactory);
    iSerializer = this.Create<int>(xmlDataContractSerializerFactory);
}
	}
}
