// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework;
using NUnit.Framework;

namespace Linq2Rest.Implementations
{
	public partial class XmlRestClientTests
	{
[Test]
[PexGeneratedBy(typeof(XmlRestClientTests))]
[ExpectedException(typeof(ArgumentNullException))]
public void ConstructorThrowsArgumentNullException520()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      XmlRestClient xmlRestClient;
      xmlRestClient = this.Constructor((Uri)null);
      disposables.Add((IDisposable)xmlRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(XmlRestClientTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException331()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      XmlRestClient xmlRestClient;
      uri = new Uri("  \\\\-");
      xmlRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)xmlRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(XmlRestClientTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException244()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      XmlRestClient xmlRestClient;
      uri = new Uri("  \\\\0");
      xmlRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)xmlRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(XmlRestClientTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException471()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      XmlRestClient xmlRestClient;
      uri = new Uri("  aa:");
      xmlRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)xmlRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(XmlRestClientTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException690()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      XmlRestClient xmlRestClient;
      uri = new Uri("  /\\\u00a0");
      xmlRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)xmlRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(XmlRestClientTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException470()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      XmlRestClient xmlRestClient;
      uri = new Uri("  a0a:");
      xmlRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)xmlRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(XmlRestClientTests))]
[ExpectedException(typeof(ArgumentException))]
public void ConstructorThrowsArgumentException855()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      XmlRestClient xmlRestClient;
      uri = new Uri("  x0x:\\/");
      xmlRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)xmlRestClient);
      disposables.Dispose();
    }
}
[Test]
[PexGeneratedBy(typeof(XmlRestClientTests))]
[Ignore("the test state was: path bounds exceeded")]
public void Constructor01()
{
    using (PexDisposableContext disposables = PexDisposableContext.Create())
    {
      Uri uri;
      XmlRestClient xmlRestClient;
      uri = new Uri(
                   "  a0x:x\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0:::::::::::::::::::::"
                   );
      xmlRestClient = this.Constructor(uri);
      disposables.Add((IDisposable)xmlRestClient);
      disposables.Dispose();
    }
}
	}
}
