// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Linq2Rest.Provider;
using Microsoft.Pex.Framework.Explorable;
using System.Collections.Generic;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace Linq2Rest.Implementations
{
	public partial class XmlSerializerFactoryTests
	{
		[Test]
		[PexGeneratedBy(typeof(XmlSerializerFactoryTests))]
		[Ignore("the test state was: path bounds exceeded")]
		public void Create770()
		{
			XmlSerializerFactory xmlSerializerFactory;
			ISerializer<int> iSerializer;
			Type[] types = new Type[0];
			xmlSerializerFactory = PexInvariant.CreateInstance<XmlSerializerFactory>();
			PexInvariant.SetField<IEnumerable<Type>>
				((object)xmlSerializerFactory, "_knownTypes", (IEnumerable<Type>)types);
			PexInvariant.CheckInvariant((object)xmlSerializerFactory);
			iSerializer = this.Create<int>(xmlSerializerFactory);
		}

		[Test]
		[PexGeneratedBy(typeof(XmlSerializerFactoryTests))]
		[PexRaisedException(typeof(ArgumentNullException))]
		public void CreateThrowsArgumentNullException94()
		{
			XmlSerializerFactory xmlSerializerFactory;
			ISerializer<int> iSerializer;
			Type[] types = new Type[1];
			xmlSerializerFactory = PexInvariant.CreateInstance<XmlSerializerFactory>();
			PexInvariant.SetField<IEnumerable<Type>>
				((object)xmlSerializerFactory, "_knownTypes", (IEnumerable<Type>)types);
			PexInvariant.CheckInvariant((object)xmlSerializerFactory);
			iSerializer = this.Create<int>(xmlSerializerFactory);
		}
	}
}
